# Generated by Django 5.1 on 2024-08-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_m_category_p_category_alter_material_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
