# Generated by Django 5.1 on 2024-08-22 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_p_category_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_category',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='p_category',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
