# Generated by Django 5.1 on 2024-08-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_m_category_name_alter_p_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='supplier',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
