# Generated by Django 5.1 on 2024-09-01 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_supplier_alter_material_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='picture',
            field=models.ImageField(blank=True, default='user.png', null=True, upload_to=''),
        ),
    ]
