# Generated by Django 5.1 on 2024-09-05 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_material_quantity_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(max_length=200, null=True),
        ),
    ]
