# Generated by Django 5.1 on 2024-09-06 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_material_quantity_alter_product_stock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='material',
            old_name='quantity',
            new_name='stock',
        ),
    ]
