# Generated by Django 5.1 on 2024-09-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_alter_productmaterial_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.DeleteModel(
            name='ProductMaterial',
        ),
    ]
