# Generated by Django 5.1 on 2024-09-19 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_remove_product_materials_delete_productmaterial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_used', models.IntegerField(null=True)),
                ('material', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.material')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='materials',
            field=models.ManyToManyField(blank=True, related_name='products', through='home.ProductMaterial', to='home.material'),
        ),
        migrations.AddConstraint(
            model_name='productmaterial',
            constraint=models.UniqueConstraint(fields=('product', 'material'), name='unique_ProductMaterial'),
        ),
    ]
