# Generated by Django 5.1 on 2024-10-15 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_product_picture_alter_material_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
