# Generated by Django 5.1 on 2024-10-15 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_alter_material_picture_alter_product_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture',
        ),
    ]
