# Generated by Django 5.1 on 2024-10-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_material_picture_remove_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='product_empty.jpeg', null=True, upload_to=''),
        ),
    ]
