# Generated by Django 5.1 on 2024-10-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_product_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='picture',
            field=models.ImageField(blank=True, default='material_empty.jpeg', null=True, upload_to=''),
        ),
    ]
