# Generated by Django 5.1 on 2025-02-27 12:38
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0030_material_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, null=True)),
            ],
        ),
    ]