# Generated by Django 5.1 on 2025-02-27 12:39
from django.db import migrations, models

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0031_create_colour_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='temp_colour',
            field=models.CharField(max_length=150, null=True, blank=True),
        ),
    ]