# Generated by Django 5.1 on 2025-02-27 12:40

from django.db import migrations

def copy_colour_values(apps, schema_editor):
    Material = apps.get_model('home', 'Material')
    for material in Material.objects.all():
        material.temp_colour = material.colour
        material.save()

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0032_add_temp_colour'),
    ]

    operations = [
        migrations.RunPython(copy_colour_values),
    ]