# Generated by Django 5.1 on 2025-02-27 12:41

from django.db import migrations

def clear_colour_values(apps, schema_editor):
    Material = apps.get_model('home', 'Material')
    Material.objects.all().update(colour=None)

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0033_copy_colour_to_temp'),
    ]

    operations = [
        migrations.RunPython(clear_colour_values),
    ]