# Generated by Django 5.1 on 2025-02-27 12:42

from django.db import migrations, models
import django.db.models.deletion

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0034_clear_colour_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='colour',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.colour'),
        ),
    ]