# Generated by Django 5.1 on 2025-02-27 12:43

from django.db import migrations

def populate_and_link_colours(apps, schema_editor):
    Material = apps.get_model('home', 'Material')
    Colour = apps.get_model('home', 'Colour')
    
    # Get all unique colour names
    colour_names = set()
    for material in Material.objects.all():
        if material.temp_colour:
            colour_names.add(material.temp_colour)
    
    # Create colour objects and keep a mapping
    colour_mapping = {}
    for name in colour_names:
        colour_obj = Colour.objects.create(name=name)
        colour_mapping[name] = colour_obj
    
    # Update materials with the appropriate colour objects
    for material in Material.objects.all():
        if material.temp_colour:
            material.colour = colour_mapping.get(material.temp_colour)
            material.save()

class Migration(migrations.Migration):
    dependencies = [
        ('home', '0035_alter_colour_to_fk'),
    ]

    operations = [
        migrations.RunPython(populate_and_link_colours),
    ]