# Generated by Django 5.1 on 2025-05-17 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_alter_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='picture',
            field=models.ImageField(blank=True, default='material_empty.jpeg', null=True, upload_to='materials/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, default='product_empty.jpeg', null=True, upload_to='products/'),
        ),
    ]
